spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/a123?serverTimezone=UTC
  redis:
    port: 6379
    host: localhost
mybatis:
  mapper-locations: classpath:mapper/*.xml
